### ISSUE TITLE
[claim rewards] contract owner cannot be change

### ISSUE THREAD

**Issue by bb111189** [Decentralised-Monsters/demons-scilla#14]
Admin cannot be changed. This may be restrictive in the event of a need to change the wallet address of the admin

Solution
Add transition to support changing of admin
https://scilla.readthedocs.io/en/latest/scilla-tips-and-tricks.html#transfer-contract-ownership

**Comment by teye** [comment]
Fixed https://github.com/Decentralised-Monsters/demons-scilla/commit/a3b306807e503cc78f300c1bc7912b510a0fbf06
