### ISSUE TITLE
[marketplace] Changing of contract owner is not possible

### ISSUE THREAD

**Issue by bb111189** [Decentralised-Monsters/demons-scilla#18]
The contract owner controls many aspects of the marketplace contracts. It will be better to have an option to change the contract owner. 

https://scilla.readthedocs.io/en/latest/scilla-tips-and-tricks.html#transfer-contract-ownership

**Comment by teye** [comment]
Fixed https://github.com/Decentralised-Monsters/demons-scilla/commit/a3b306807e503cc78f300c1bc7912b510a0fbf06
