### ISSUE TITLE
[marketplace] bound commission rate 

### ISSUE THREAD

**Issue by bb111189** [Decentralised-Monsters/demons-scilla#21]
The commission rate should be check to ensure it is between 0 to 100%. Right now, it is possible to set the commission rate up to Iint128.

**Comment by hicaru** [comment]
which one contract about you?

**Comment by bb111189** [comment]
```
transition UpdateCommission(new_commission: Uint128)
  IsContractOwner;
  old_com <- commission;
  commission := new_commission;
  e = {
    _eventname: "UpdateCommission";
    previous_commission: old_com;
    new_commission: new_commission
  };
  event e
end
```
Marketplace.scilla 

This is an admin function. But it is good to add checks to prevent the admin from making mistakes. It can also help in formal verification if anyone is working on it :)

**Comment by teye** [comment]
Fixed https://github.com/Decentralised-Monsters/demons-scilla/commit/2b2fc90655174c248bf651399a98e3ba2edde73c
